title: Living Off The Cloud
description: A repository for native cloud techniques used by Threat Actors
theme: just-the-docs

url: https://github.com/lotcloud/living-off-the-cloud

aux_links:
  GitHub: https://github.com/lotcloud/living-off-the-cloud

just_the_docs:
  collections:
    techniques:
      name: Techniques
      nav_exclude: false
      search_exclude: false

collections:
  techniques:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    techniques:
      nav_exclude: true

defaults:
  - scope:
      path: ""
      type: "techniques"
    values:
      layout: "technique"
      search_exclude: false
      nav_exclude: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"